name: Run test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code version from git
        uses: actions/checkout@v2
        with: 
          path: ./

      - name: Set up Python environement
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Run all tests
        run: pytest ./tests/
