name: auto update-data

on:
  push:
    branches: master
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  update-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code version from git
        uses: actions/checkout@master
        with:
          path: ./

      - name: Set up Python environement
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch data
        run: ./shell_script/update_data.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




